// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoJZGO_9U4Q2R6TS61P5m3KjmHvzQWHmk',
    appId: '1:233299560463:web:3fe1fcab703d18fbf23b7a',
    messagingSenderId: '233299560463',
    projectId: 'iehapppizzaorder',
    authDomain: 'iehapppizzaorder.firebaseapp.com',
    databaseURL: 'https://iehapppizzaorder-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iehapppizzaorder.appspot.com',
    measurementId: 'G-2ZX0XEWPFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfgqglxl8Y1sqcq0on7kyrZlzbA-PdJVQ',
    appId: '1:233299560463:android:0c6c47112cac4408f23b7a',
    messagingSenderId: '233299560463',
    projectId: 'iehapppizzaorder',
    databaseURL: 'https://iehapppizzaorder-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iehapppizzaorder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9RgI2dAFqpg0qAjKMAo_oT0x-YZ9cSe0',
    appId: '1:233299560463:ios:bcacd58b3ced22bdf23b7a',
    messagingSenderId: '233299560463',
    projectId: 'iehapppizzaorder',
    databaseURL: 'https://iehapppizzaorder-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iehapppizzaorder.appspot.com',
    iosClientId: '233299560463-kha9pgpd1ava3f0au67cnpgenvan5qgu.apps.googleusercontent.com',
    iosBundleId: 'com.iehapp.pizzaorder.pizzaOrder',
  );
}
